language: csharp
jobs:
  include:
  - os: linux
    dotnet: 3.0.100
    mono: none
  - os: osx
    osx_image: xcode11
    dotnet: 3.0.100
    mono: none
script:
- dotnet restore ./src/Vlingo.Http.sln; dotnet build ./src/Vlingo.Http.sln; dotnet
  test ./src/Vlingo.Http.Tests/Vlingo.Http.Tests.csproj;
notifications:
  slack:
    secure: LQFdcvF6Mm2CGWyW2PB8k8y6m/1xEQL0ddhCspHAN9G7vEzBv5yRQ4UOzrv6fiaG94ncrhhLf4djS8cIi8xF8Yqgdc9eb1Ti+5DmreE42Hoh8pHZf9BSH2mEN0xffOK8woNqf0SKsKygtP6sBP6TVMz5mD750TWuOlL+6PBedDHSNt5+IKPgaw92hPesbwAez41R0N93njoXG8jqLoWOhepQxFol0ElMboOZrnm7aTGPd5jG+7dK7DPsOXaZvQo8T7Q+A+x+DSoeJ/bcJXkDtfSGPsYcpByzfKW4/4oZThGWkjtoLUUlm5alkvjWtKa9UVkCbY2yILGyVuiLmaXQJLyuPk8l3V6YUIs8a0fz9IiBBjPmkMalGUMERINipNaLQCaSfpHdzhACO9nj9sOdMQf+08gI0dTWxgSBaMuqzRTU6/k8Y5GD4m4t5Ip9GaW6rqPKAeYqZ6+7oPrxv24uv+fIaIjO7WYI0avvy1YjbfMVwYFMczEch2J+0AWPw1igQ+juVmIhAQLGU0n03I6Gkc9MZBi5Wbbjs+YqizKBVUvY3lsneu5IkzNWq48nX3TvRJdNAxxcYMNg11EPn1ZYx9vOpOJSBm7/wHTHG2SE8axZ5pmnpKxMbocCEmlM++p6/r9RB/mKcQcSdnJiou4/tVO3R0RYM4b4oAriwjQ1j3c=
